// app-packages/vue-app/src/App.vue
<template>
  <div class="App-nav">
    <img class="App-logo" alt="Vue logo" src="./assets/logo.png">
    <h2>ue</h2>
    <div class="nav-links-container">
      <router-link class="App-link" to="/todos">Todos</router-link>
      <router-link class="App-link" to="/completed-todos">Completed Todos</router-link>
    </div>
  </div>
  <router-view/>
</template>

<script>
import { onMounted, provide, readonly } from "vue";
import { todoState, stateApi } from "./state";

  export default {
    setup() {
      provide('todoState', readonly(todoState))
      provide('stateApi', readonly(stateApi))

      onMounted(() => {
        stateApi.fetchTodos()
      })
    }
  }
</script>

<style>

#nav a {
  font-weight: bold;
  color: #2c3e50;
}

</style>

// react-app/src/App.js
import logo from './logo.svg';
import './App.css';

import React from "react";
import {
  BrowserRouter as Router,
  Switch,
  Link
} from "react-router-dom";

import { routesRendererMap } from "./router/routeConfig";

import { TodoStateProvider } from "./state";

export default function TodoApp() {
  return (
      <TodoStateProvider>
          <Router>
              <nav className="App-nav">
                  <img className="App-logo" src={logo} alt="React Logo" width={75}/>
                  <div className="nav-links-container">
                <span>
                    <Link to="/todos" className="App-link">Todos</Link>
                </span>
                      <span>
                    <Link to="/completed-todos" className="App-link">Completed Todos</Link>
                </span>
                  </div>

              </nav>
              <Switch>
                  { routesRendererMap }
              </Switch>
          </Router>
      </TodoStateProvider>
  )
}
